### ISSUE TITLE
HTML Clean up and Validation

### ISSUE THREAD

**Issue by allella** [magoun/sccodes-php-track-project#1]
These would be good tasks for the hack day.

There are a number of HTML validation issues I notice, but it's always nice to run things through an validator https://validator.w3.org/

- need quotes around the href for the Google calendar links and also it's missing a closing tag
- unnecessary <br> tags between the <option> tags
- duplicate <html> tag near the top
- the ul/li around the Google calendar link seems unnecessary since it's only a single value and not a list
- always a good idea to make local links absolute, excluding the domain. So, /css/somefile.css instead of css/somefile.css. 
- Some of the links in <head> like <link and script> would be better absolute too.  Being relative can be helpful in a dev mode but seems like it causes more accidents that are harder to catch then making everything absolute. 
- Unless they changed this in HTML 5, <link> tags can/should be self closing  <link ..../>

**Comment by magoun** [comment]
The above commit fixes #1 on the upstream repo, link [here](https://github.com/codeforgreenville/hackgreenville-com/issues/1).
